var VECTORS = {
  'U' : { x: 0, y: -1 },
  'R' : { x: 1, y: 0 },
  'D' : { x: 0, y: 1 },
  'L' : { x: -1, y: 0 }
};

var BathroomDecoder = function(start, instructions) {
  this.currentButton = start;
  this.instructions = instructions.split('');

  this.isValid = function(newButton) {
    return (Math.abs(newButton.y) <= 2 && Math.abs(newButton.x) <= (2- Math.abs(newButton.y)))
  }

  this.followInstruction = function(instruction) {
    var newButton = {
      x: this.currentButton.x,
      y: this.currentButton.y
    };
    var instructionVector = VECTORS[instruction];
    newButton.x += instructionVector.x;
    newButton.y += instructionVector.y;
    if (this.isValid(newButton)) {
      this.currentButton = newButton;
    }
  }

  this.followInstructions = function() {
    for (var i = 0; i < this.instructions.length; i++) {
      this.followInstruction(this.instructions[i]);
    }
  }
};
//
// var firstNumber = new BathroomDecoder({ x: -2, y: 0 }, 'ULL');
// firstNumber.followInstructions();
// console.log(firstNumber.currentButton);
// var secondNumber = new BathroomDecoder(firstNumber.currentButton, 'RRDDD');
// secondNumber.followInstructions();
// console.log(secondNumber.currentButton);
// var thirdNumber = new BathroomDecoder(secondNumber.currentButton, 'LURDL');
// thirdNumber.followInstructions();
// console.log(thirdNumber.currentButton);
// var fourthNumber = new BathroomDecoder(thirdNumber.currentButton, 'UUUUD');
// fourthNumber.followInstructions();
// console.log(fourthNumber.currentButton);

var firstNumber = new BathroomDecoder({ x: -2, y: 0 }, 'DULUDRDDDRLUDURUUULRRRURDRDULRUDDUDRULUDDUDRLDULRRLRDRUDUUULUUDLRURDUDDDDRDLLLLULRDLDRDLRLULRUURDDUULUDLRURRDDRDDRDDLDRDLLUURDRUULRRURURRDLRLLLUDULULULULUDRLLRUDUURLDRLRLRDRRDRLLLDURRDULDURDDRLURRDURLRRRLDLLLDRUUURLRDLDLLLLRDURRLDLULRLDDLDLURLRRDDRUDDUULRURRUDLRDLDUURDDDDRLRURUDULUDLRRLLLLLRDRURLLDLDULUUDLUDDDRLLDRRUDLLURRUUDDRRLLRRLDDDURLDRDRLURRRRDRRRDDUDULULDURRUUURRRDULUUUDDRULDRLLRDLDURLURRLLRUUUULRDURLLDDRLLDLRLRULUUDRURUDLLURUDDRDURLRDRRRDURLDDRDRLRLLURULUUULUDDDULDLRDDDRDLLRRLDRDULLUUUDLDDLDDDLLLLLLLDUDURURDURDRUURRRDDRDUDLULDURDUDURDDDRULDURURURRLURLURLUURLULDLLRUULURDDRLRDDLRDLRRR');
firstNumber.followInstructions();
console.log(firstNumber.currentButton);
var secondNumber = new BathroomDecoder(firstNumber.currentButton, 'LUURLRUDRRUDLLDLUDDURULURLUUDUUDDRLUULRDUDDUULDUUDRURDDRRDRLULLRDRDLRLLUURRUULRLDRULUDLDUUDDDRDDLRDLULDRLDUULDLRDLLLDLDLRDUULUDURRULLRLDUDRLLLULUUUULUUDUUURRRDULLUURUDRRLDURRUULDRDULDUDRDUUULUUDDRLUDRLDLDRUUURDLDUDRUDUURLLRRLRLLRRLDULDDULUDUUURULDDUDUDRURRDLULRUDDURDLDLLRRRLDRLULLLRUULDUDLUUDURRLLLRLUDURRDDLDRDDDLURDLDRRUDUDLUDULULRUUUDLUURLLRLDDLURULDURDLRRDDDDURLDDLLDDULLLRLDLDULDUUDDRLDUURDDLDLUUDULRRLRLUURURUURLRLURUURLDRUURLLRDDUUUDULUDDDRDRLDRDRRLRLDULLRRUDLURULULRDRURURLULDUDLRURLRDDRULDDLRD');
secondNumber.followInstructions();
console.log(secondNumber.currentButton);
var thirdNumber = new BathroomDecoder(secondNumber.currentButton, 'LUDRULUULRRDDDDRRDUURUDDRLDDLDRDURRURULRDLDLDUUDRRDUUDUDLLLRRLDUDDRLDDLRRLRDRLUDLULUDDUUDULDUUULUDLDDURLDURUDLDRUUDRLRRLDLDDULDUUDDLDDLLURDRLRUURDDRUDDUDLDRRLRUDRUULRRRLRULULURDLRRURDRLRULDDDRDUULLURUUUURUDDLRRRRRDURLULDLUULUDRRUDUDRRDDRURDURLRLUDDLDLRRULUDLDDRLDDLDDDLLLLRDLLUULDDLULDLDRDDUDLURUDLDLDDRRUUDDDLRLLLDRRDDDUURDUDURUURRDRLLDUDLDUULLDLDLLUULLRRULDLDRURLDULDRUURDURRURDLRDLLLDRRUDRUUDRURLUDDRURLDURRDLUUDLUUDULLLDDDDRRDLLLDLURULDDRDLUUURRDRRUUDDUL');
thirdNumber.followInstructions();
console.log(thirdNumber.currentButton);
var fourthNumber = new BathroomDecoder(thirdNumber.currentButton, 'DUUULDUDDDURLLULDDLLUDURLLLURULULURUURDRURLRULLLLDRDDULRRDRRLLLRDDDUULLRRURRULLDDURRRLRDDLULDULLDUDLURRDLDDLURDLRLLDRURLLRLLRRRDRRRURURUUDDLLDDLDDDLRLURUUUULRDLUDDDURLLDDRLDRRLLUDUUULRLLDRRRLRUUDLDUULRLUDRULLLLDUDLLUUDDRUURLURUDRDDDLRURUDRLULLULUUDLDURDULRRDRLDURUULRDRRRDRDRRLRLRDDUULLRDLDURDDDULURRLULDDURDURDDUDURDLLUUULUDULRDDLDRDRUDLLUURDLRDURURULURULLDRLLRRULDLULULDLULRURLRRLUDLLLRLUDLURLULDULDRLLLDLDDDDRDRLRRLRDULUUDULDDLDURDLLLDDDDLLUURRDURLDLUDDLULRUUUDDRRLDLLLRDLLDRRRDDLULLURDDRRRRLDLRLLLRL');
fourthNumber.followInstructions();
console.log(fourthNumber.currentButton);
var fifthNumber = new BathroomDecoder(fourthNumber.currentButton, 'LULLRRDURRLDUUDRRURLURURRRLRDRUULUULURLLURRDRULRDURDDDDUULLLLDUULDLULURDRLDLULULDRLLDLLRLRULURUDRUUDULRULLLUDRULUDRLLUDLDRRDRUUURURLRDURDRLRDDDURLURRDLRUUUDUURULULDLUULRDLRRRDRDRLLLDLRRDRLLDDULDRUDRRLULLRDLDUDDULRDDLULRURULRLLLULDLLLLRDLDRURUDUURURLDRLUULLDUDULUDDDULUDLRUDDUDLULLUULUUURULURRULRDDURDDLURLRRDRDLDULRLRDRRRULRDDDRLLDDDDRRRRDRDLULUURDURULDLRDULDUDLDURUDLUDLUDDDUDURDURDDURLLRUDUURRRUDRRRRULLLLDDDLUULLUULRRRULDLURDLULRULDRLR');
fifthNumber.followInstructions();
console.log(fifthNumber.currentButton);
